### ISSUE TITLE
my own theme/build

### ISSUE THREAD

**Issue by sergiokopplin** [sergiokopplin/kopplin-website#8]
### task: delete the actual theme (kasper) and create my own theme.

- [ ] medium components
- [ ] [flexbox](https://gist.github.com/sergiokopplin/11dc134980d4129f660b)
- [ ] [publish](http://jekyllthemes.org/) theme
- [ ] [monokai]( https://gist.githubusercontent.com/markfknight/9822503/raw/a14583dfe19301a00a0aca57302969e768e7101d/jekyll_monokai_pygments.css)
- [ ] meta tags fot tags
- [ ] search system

**Comment by sergiokopplin** [comment]
# Fonts.

 - Open Sans & Open Sans (William Justen).
 - Helvetica Neue & Helvetica Neue (Hugo Bessa).
 - Open Sans & Droid Serif (Nomadev).
 - Vollkorn & PTSans.
 - Lato & Noto Serif.

**Comment by sergiokopplin** [comment]
# Layout Ideias:

<img width="954" alt="screen shot 2015-10-12 at 6 46 09 pm" src="https://cloud.githubusercontent.com/assets/2743180/10439622/8b06785a-7111-11e5-9bb4-5ede7d319fff.png">

<hr>

<img width="939" alt="screen shot 2015-10-12 at 6 50 24 pm" src="https://cloud.githubusercontent.com/assets/2743180/10439706/1ff7ba1e-7112-11e5-9e84-c17c9149885e.png">

<hr>

<img width="747" alt="screen shot 2015-10-12 at 6 51 20 pm" src="https://cloud.githubusercontent.com/assets/2743180/10439724/45ed5b48-7112-11e5-989e-aa67b692330e.png">

<hr>

<img width="842" alt="screen shot 2015-10-12 at 6 54 01 pm" src="https://cloud.githubusercontent.com/assets/2743180/10439769/a38462ba-7112-11e5-83c1-e48bebfd8d03.png">

<hr>

<img width="649" alt="screen shot 2015-10-12 at 6 54 24 pm" src="https://cloud.githubusercontent.com/assets/2743180/10439774/af5cc636-7112-11e5-9d53-12d70bed1e5e.png">

<hr>

<img width="1105" alt="screen shot 2015-10-12 at 6 56 26 pm" src="https://cloud.githubusercontent.com/assets/2743180/10439810/f73290ee-7112-11e5-9d2d-4fdc9e469a40.png">

<hr>

<img width="1068" alt="screen shot 2015-10-12 at 6 56 47 pm" src="https://cloud.githubusercontent.com/assets/2743180/10439816/011ed3f6-7113-11e5-9eef-a656f2398926.png">

<hr>

<img width="713" alt="screen shot 2015-10-12 at 6 57 19 pm" src="https://cloud.githubusercontent.com/assets/2743180/10439826/16a29d20-7113-11e5-8919-3892febf951f.png">

<hr>

<img width="697" alt="screen shot 2015-10-12 at 6 57 41 pm" src="https://cloud.githubusercontent.com/assets/2743180/10439838/24c685c4-7113-11e5-944a-50ed50285f0c.png">

<hr>

<img width="292" alt="screen shot 2015-10-12 at 6 58 07 pm" src="https://cloud.githubusercontent.com/assets/2743180/10439852/33d62ace-7113-11e5-921c-0c8074a03350.png">

<hr>

<img width="226" alt="screen shot 2015-10-12 at 6 59 27 pm" src="https://cloud.githubusercontent.com/assets/2743180/10439879/679636ec-7113-11e5-8452-fce4c43287b2.png">

**Comment by sergiokopplin** [comment]
# Best referencies:

http://themeforest.net/item/forest-woody-theme/11041014
http://forest-themeghost.rhcloud.com/

http://purus.golem.io/new-post-cover-images/

http://pellere.golem.io/

VERY GOOD: http://urban-themeghost.rhcloud.com/
http://themeforest.net/item/urban-ghost-theme/12158030

https://fairytale-bdinfosys.rhcloud.com/
https://creativemarket.com/bdinfosys/279928-Fairytale-Blogging-Theme-for-Ghost

**Comment by sergiokopplin** [comment]
# More layout ideias

<img width="1332" alt="screen shot 2015-10-12 at 7 00 13 pm" src="https://cloud.githubusercontent.com/assets/2743180/10439886/7c21aff6-7113-11e5-8761-a50b1ccd69b9.png">

<hr>

**Comment by sergiokopplin** [comment]
### Medium components inspiration

<img width="1231" alt="screen shot 2015-10-13 at 9 21 27 pm" src="https://cloud.githubusercontent.com/assets/2743180/10471859/6e0050b6-71f0-11e5-93be-4845e3d2d6d2.png">

<hr>

Componente grudado na esquerda

![screen shot 2015-10-13 at 9 22 18 pm](https://cloud.githubusercontent.com/assets/2743180/10471875/8aae72b0-71f0-11e5-8143-d2fb25d7694b.png)

<hr>

Imagens ao lado de textos

![screen shot 2015-10-13 at 9 23 01 pm](https://cloud.githubusercontent.com/assets/2743180/10471883/9fd64212-71f0-11e5-9839-dd6d6bf30816.png)

<hr>

Estilo das tags

![screen shot 2015-10-13 at 9 23 33 pm](https://cloud.githubusercontent.com/assets/2743180/10471909/b552f7b6-71f0-11e5-874e-3003dcab9f95.png)

<hr>

Topo que surge e desaparece com scroll

![screen shot 2015-10-13 at 9 23 58 pm](https://cloud.githubusercontent.com/assets/2743180/10471913/c2296600-71f0-11e5-93d8-e99449fc455c.png)

<hr>

Legenda de imagens

![screen shot 2015-10-13 at 9 25 13 pm](https://cloud.githubusercontent.com/assets/2743180/10471927/eebe7034-71f0-11e5-8bc7-2b546b029fb3.png)

<hr>

Componente do rodapé

![screen shot 2015-10-13 at 9 26 02 pm](https://cloud.githubusercontent.com/assets/2743180/10471936/0a3df708-71f1-11e5-9fa2-8a2bdac9ba14.png)

<hr>

Artigos com imagens

![screen shot 2015-10-13 at 9 26 42 pm](https://cloud.githubusercontent.com/assets/2743180/10471940/219f41cc-71f1-11e5-8b84-14d3cf7c6295.png)

<hr>

Marca texto

![screen shot 2015-10-13 at 9 27 16 pm](https://cloud.githubusercontent.com/assets/2743180/10471944/352278e0-71f1-11e5-9215-66e8fc765fcc.png)

<hr>

Outras leituras

![screen shot 2015-10-13 at 9 27 51 pm](https://cloud.githubusercontent.com/assets/2743180/10471953/4b6fc256-71f1-11e5-8dfc-354f368a8130.png)

**Comment by sergiokopplin** [comment]
#### creativepug referencies:

![01_skater_girl](https://cloud.githubusercontent.com/assets/2743180/10494298/f29d6fd4-728b-11e5-83d9-c5411d372459.png)

<hr>

essa imagem no canto direito (:

![landing-idea-final](https://cloud.githubusercontent.com/assets/2743180/10494348/460d5602-728c-11e5-8a70-e5c9606943ac.jpg)

**Comment by sergiokopplin** [comment]
an very very bad wireframe

![img_20151015_190202084_hdr](https://cloud.githubusercontent.com/assets/2743180/10528864/61f4f7a6-736f-11e5-98fd-735aeb3dd42c.jpg)

**Comment by sergiokopplin** [comment]
colors:

#6DFFD6

**Comment by sergiokopplin** [comment]
ideia da página que carrega com o logo do kopplin e depois mostra baterista programador de narnia com fade

**Comment by sergiokopplin** [comment]
http://www.verse-co.com/

**Comment by sergiokopplin** [comment]
moving the final tasks to another issue
